1. asocierea unuiu grad de incredere pentru fiecare geocodare 
2. Geocodare firmelor folosind dexonline ( vezi src/format.py  ). Utilizand un levenshtein modificat care sa tina cont de ponderi ( sa returneze % ),
	se mai pot geocodat multe firme. Ideea poate fi refolosita in foarte multe locuri. 
	
3. * Adaugare numere postale - as fi interesant de integrat ideea cu editare online si salvare pe git. 